name: Build and Push Docker Image

on:
  push:
    branches:
      - master
      - test-build
  workflow_dispatch:

jobs:
  # First job to request approval
  request-approval:
    runs-on: ubuntu-latest
    steps:
      - name: Request approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.GITHUB_TOKEN }}
          approvers: DenisStefanAndrei,alinmanolache,AlexCornigeanu,marian-craciunescu,marius-avram,mateibm,AndreiTudose95,smmihai,RazvanKokovicsSiscale,hutanmihai,aburnaz
          minimum-approvals: 1
          issue-title: "Approval needed for Docker image push"
          issue-body: "Please approve this workflow to push a new Docker image to DockerHub"
          exclude-workflow-initiator-as-approver: false
          timeout-minutes: 120

  # Second job to build and push Docker image
  build-and-push:
    needs: request-approval  # This ensures the approval job completes first
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: devsiscale
          password: ${{ secrets.DOCKERHUB_DEVSISCALE_PAT }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: arcanna/arcanna-mcp-server:latest